name: CI-CD
on:
  push:
    branches:
      - main
      - Develop

jobs:
  build:
      name: build
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js 20
          uses: actions/setup-node@v4
          with:
            node-version: "20"
        - name: Install dependencies
          run: npm install
          working-directory: meditacao-app
        - name: Run build
          run: npm run build
          working-directory: meditacao-app