name: CI-CD
on:
  push:
    branches:
      - main
      - Develop
      - Iza
      - Thomas
      - Gabriella
      - Marcos

jobs:
  build:
      name: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Use Node.js 20
          uses: actions/setup-node@v4
          with:
            node-version: "20"

        - name: Install dependencies
          run: npm install
          working-directory: meditacao-app

        - name: Run build
          run: npm run build
          working-directory: meditacao-app

        - name: Upload build artifact
          uses: actions/upload-artifact@v4
          with:
            name: mantra-build
            path: meditacao-app
  
  test:
    name: Running unit-tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: meditacao-app

      - name: Run unit tests
        run: npm run test -- --verbose 
        working-directory: meditacao-app

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: meditacao-app/coverage
